
function getEvents(print = false) {

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", $('#events-route').val(), true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			var minTime = (print) ? '08:00:00' : '00:00:00';
		    $('#calendar').fullCalendar({
		    	lang: '<?php echo substr($context->getLocale(), 0, 2) ?>',
		    	height: 650,
		        defaultView: 'agendaWeek',
		        scrollTime: '08:00:00',
		        minTime: minTime,
		        businessHours: {
				   	dow: [ 1, 2, 3, 4, 5, 6], // Monday - Thursday
				    start: '08:00',
				    end: '18:00'
			    },
				customButtons: {
			        myCustomButton: {
			            text: '<?php echo $this->translate('Printable', 'ppit-document', $context->getLocale()) ?>',
			            click: function() {
			                window.open('<?php echo $this->url('public/communityHomePrint') ?>');
			            }
			        }
			    },
    			header: {
				    left: 'prev,next today myCustomButton',
				    center: 'title',
				    right: 'month,agendaWeek,agendaDay'
				}
    		});
			obj = jQuery.parseJSON(xhttp.responseText);

			jQuery.each(obj.planning, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.properties['category'] == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var title = value.properties['property_3'];
				if (value.properties['caption']) title += ' - ' + value.properties['caption'];
				if (value.properties['location']) title += ' (' + value.properties['location'] + ')';
				var event={
					id:value.id,
					title: title,
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['begin_time']), 
					end:  $.fullCalendar.moment(value.properties['begin_date'] + ' ' + value.properties['end_time'])
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});

			jQuery.each(obj.events, function (name, value) {
				var color = 'lightBlue', textColor = 'black';			
<?php foreach ($context->getConfig('commitmentEvent/p-pit-studies')['category'] as $categoryId => $category) : ?>
	<?php foreach ($category['color'] as $color => $unused) : ?>
				if (value.category == '<?php echo $categoryId ?>') {
					color = '<?php echo $color ?>';
					textColor = 'white';
				}
	<?php endforeach;?>
<?php endforeach;?>

				var event={
					id:value.id,
					allDay: true,
					title: value.title + ' (' + value.location + ')',
					color: color,
					textColor: textColor,
					start:  $.fullCalendar.moment(value.begin_time), 
					end:  $.fullCalendar.moment(value.end_time)
				};
				$('#calendar').fullCalendar('renderEvent', event, true);
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function showStatic(route, target) {
	// Execute the ajax request
	var xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById(target).innerHTML = xhttp.responseText;
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function showCalendar(route, target) {
	// Execute the ajax request
	var xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById(target).innerHTML = xhttp.responseText;
			getEvents();
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}
