
function connectRemoveIcon(parent_id, id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		filterDocumentList(parent_id);
	});
}

function getParams() {

	// Create a new FormData object.
	var params = '?', todo = true;

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
		<?php $property = $context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId] ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;

		<?php if ($property['type'] == 'date') : ?>
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
		<?php else : ?>
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = min_<?php echo $propertyId ?>;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = max_<?php echo $propertyId ?>;
		<?php endif;?>

	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }		
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
		<?php $property = $context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId] ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;

		<?php if ($property['type'] == 'date') : ?>
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
		<?php else : ?>
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = min_<?php echo $propertyId ?>;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = max_<?php echo $propertyId ?>;
		<?php endif;?>

	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }		
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

	<?php
	$todoTitle = $context->getInstance()->specifications['ppitDocument']['document/search']['todoTitle']['fr_FR'];
	$searchTitle = $context->getInstance()->specifications['ppitDocument']['document/search']['searchTitle']['fr_FR'];
	?>
	$('#mode-text').text((todo) ? '<?php echo $todoTitle ?>' : '<?php echo $searchTitle ?>');

	return params;
}

// Export the list
function exportDocumentList(parent_id) {

	var params = getParams();
	document.location.href = '<?php echo $this->url('document/export') ?>/' + parent_id + params;
}

function eraseDocumentSearch(parent_id) {

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

	getDocumentList(parent_id, getParams(), 'name', 'ASC');
}

function sortDocumentList(parent_id, criterion) {

	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getDocumentList(parent_id, getParams(), criterion, dir);
}

function filterDocumentList(parent_id) {

	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	else if (ascCriterion) {
		criterion = descCriterion.split('-')[0];
		dir = 'DESC';
	}
	else {
		criterion = 'sequence';
		dir = 'DESC';
	}
	getDocumentList(parent_id, getParams(), criterion, dir);
}

function connectDocumentSearchInputs(parent_id) {

	$('#export-button').click(function () { exportDocumentList(parent_id); });
	
	$('#erase-button').unbind();
	$('#erase-button').click(function () { eraseDocumentSearch(parent_id); });

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });

		<?php if ($context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
	
	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });

		<?php if ($context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
		<?php endif;?>

	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/search']['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });

		<?php if ($context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });

	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterDocumentList(parent_id); });

		<?php if ($context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterDocumentList(parent_id); });
		<?php endif;?>
		
	<?php endif;?>

<?php endforeach;?>
}

// Load the list
function getDocumentList(parent_id, params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('document/list') ?>/' + parent_id + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');

	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['ppitCoreSettings']['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('document-list-panel').innerHTML = xhttp.responseText;
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortDocumentList(parent_id, $(this).attr('id').split('-')[0]);
				});
			});
			
			// Connect the detail anchors
			$('.document-detail-anchor').each(function () {
				$(this).click(function () {
					getDocumentDetail(parent_id, $(this).attr('id').split('_')[1]);
				});
			});

			// Connect the directory anchors
			$('.directory-anchor').each(function () {
				$(this).click(function () {
					getDocumentList($(this).attr('id').split('_')[1], params, major, dir);
				});
			});
	<?php if (!$config['ppitCoreSettings']['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();
}

function connectAuditPanel()
{
	$('#audit-panel').hide();
	$('#audit-label').click(function () {
		if ($('#audit-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#audit-panel').show();
			$('#audit-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#audit-panel').hide();
			$('#audit-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

function connectDocumentUpdateForm(parent_id, id, action)
{
	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
		
		var validity = true, error, number;
		val = document.getElementById('directory').value;
	    if (!val && val.length > 255) {
			renderElement('directory', "<?php echo $this->translate('The input is too long', 'ppit-core', $context->getLocale()) ?>");
			validity = false;
		}
	    else {
			renderElement('directory', null);
		}
	
		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values

			formData.append('directory', document.getElementById('directory').value);

			var fileSelect = document.getElementById('proof_id');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('proof_id', file, file.name);
				}
			}

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('document/add') ?>/' + parent_id;
			target = 'document-update-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['ppitCoreSettings']['isTraceActive']) : ?>
					console.log('post, route = ' + route);
					console.log(xhttp.responseText);
<?php endif;?>
					document.getElementById(target).innerHTML = xhttp.responseText;
					getDocumentList(parent_id, '?', 'name', 'ASC');
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getDocumentUpdate(parent_id, id) {

	var xhttp = new XMLHttpRequest();
	var route;
	if (id != 0) route = '<?php echo $this->url('document/update') ?>/' + id;
	else route = '<?php echo $this->url('document/add') ?>/' + parent_id;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('document-update-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('socument-update-panel, route = ' + route);
			console.log(xhttp.responseText);
<?php endif;?>

			connectDocumentUpdateForm(parent_id,  id);
		}
	}
	xhttp.send();
}

// Load the detail panel
function getDocumentDetail(parent_id, id) {

	// Ensure the target is displayed
	$('#form_action').show();

	// Anchor to the new panel
	$(location).attr('hash', 'form_action');

	var route = '<?php echo $this->url('document/detail') ?>' + '/' + id;

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['ppitCoreSettings']['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('form_action').innerHTML = xhttp.responseText;

//			connectAuditPanel();
			connectRemoveIcon(parent_id, 'remove-anchor', 'form_action');
			getDocumentUpdate(parent_id, id);
	<?php if (!$config['ppitCoreSettings']['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('#document-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
}

function activateDocument(parent_id) {

	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('document/search') ?>/' + parent_id);
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	var documentAnchor;
	documentAnchor = '#document-anchor';
	$(documentAnchor).removeClass("btn-default").addClass("btn-primary");

	<?php
	$todoTitle = $context->getInstance()->specifications['ppitDocument']['document/search']['todoTitle']['fr_FR'];
	?>
	$('#mode-text').text('<?php echo $todoTitle ?>');
		
	// Connect the search inputs
	connectDocumentSearchInputs(parent_id);
	
	getDocumentList(parent_id, '?', 'name', 'ASC');
	
	$('#add-criteria').click(function () {
		mode = $('#add-criteria').text();
		if (mode == '<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>') {
			$('#add-criteria').text('<?php echo $this->translate('Less criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').show();
		}
		else {
			$('#add-criteria').text('<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').hide();
		}
	});
	$('#search-area').hide();
}
