 				<table class="table-condensed">

<!-- Access path -->
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Access path', 'ppit-core', $context->getLocale())?></td>
						<td>
<?php for ($i = 0; $i < count($parent->parents); $i++) : ?>
							<?php if ($i > 0) echo ' > '; ?>
					        <?php echo $parent->parents[$i]->name; ?></strong>
<?php endfor;?>
						</td>
					</tr>
				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
		
		<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
				
<!-- Directory -->
				    <div class="form-group" id="directory_group">
						<div class="col-sm-1">
							<input type="radio" id="directory_option" class="form-control" value="1" checked="checked" <?php if ($message == 'OK') echo 'disabled="disabled"' ?>/>
						</div>
						<label class="col-sm-4 control-label"><?php echo $this->translate('Directory', 'ppit-core', $context->getLocale()) ?></label>
				    	<div class="col-sm-7">
							<input name="directory" id="directory" class="form-control" value="<?php echo $document->name ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>/>
						</div>
						<div class="col-sm-12"><p class="help-block" id="directory_error"></p></div>
					</div>

<!-- Document (only in add mode) -->
					<div class="form-group">
						<div class="col-sm-1">
							<input type="radio" id="uploaded_option" class="form-control"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>/>
						</div>
						<label class="col-sm-4 control-label"><?php echo $this->translate('Document', 'ppit-core', $context->getLocale()) ?></label>
				    	<div class="col-sm-7">
							<input type="file" name="name" id="name" class="form-control"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>/>
						</div>
					</div>
