<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
//		$this->current = 'document';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
<?php endif;?>

    	<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Document', 'ppit-customer', $context->getLocale()) ?>:
            </div>
		    <div class="panel-body">
<!-- Display the audit -->
				
				<div class="panel panel-default">
		            <div class="panel-heading">
						<strong><?php echo $this->translate($this->translate('Online visas', 'ppit-core', $context->getLocale()));?></strong>
		            </div>
					<div class="panel-body">
	<?php foreach ($document->audit as $comment) : ?>
						<div class="row">
							<div class="col-md-12">
								<strong><?php echo $context->decodeDate(substr($comment->time, 0, 10)).substr($comment->time, 10) ?>:</strong>&nbsp;
								<?php echo $this->translate($comment->status, 'ppit-core', $context->getLocale()) ?>&nbsp;
								(<?php echo $comment->n_fn ?>)
							</div>
						</div>
						<div class="row">
							<div class="col-md-2" align="right">&nbsp;</div>
							<div class="col-md-10">
								<em><?php echo $comment->comment ?></em></div>
						</div>
	<?php endforeach;?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header') ?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Comment -->

<?php
	echo $this->partial('/partials/textarea-widget.phtml', array(
		'property' => 'comment',
		'label' => $this->translate('Your comment', 'ppit-core', $context->getLocale()),
		'value' => $document->comment,
		'isMandatory' => false,
		'maxLength' => 2057,
		'rows' => 3,
		'labelWidth' => 3,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<?php if ($message == 'OK') : ?>
<!-- Foot return link -->
					<div class="form-group" id="foot_return_link">
						<div class="col-sm-5">&nbsp;</div>
						<div class="col-sm-7">
							<a id="foot-return-anchor" href="#">
								<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>
							</a>
						</div>
					</div>
<?php else : ?>

<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-3">&nbsp;</div>
						<div class="col-sm-9">
							<input name="action" type="hidden" id="action" />
							<input name="submit" type="submit" id="approve-button" class="btn btn-primary" value="<?php echo $this->translate('Approve', 'ppit-core', $context->getLocale()) ?>">
							&nbsp;&nbsp;
							<input name="submit" type="submit" id="reject-button" class="btn btn-primary" value="<?php echo $this->translate('Reject', 'ppit-core', $context->getLocale()) ?>">
							&nbsp;&nbsp;
							<a id="cancel-anchor" href="#">
								<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>
							</a>
						</div>
					</div>
<?php endif;?>

<?php if (!$context->isSpaMode()) : ?>
				</form>
<?php endif;?>
					</div>
				</div>

<!-- Display the document -->
<?php foreach ($document->parts as $part) : ?>
				<?php echo $part->content; ?>
<?php endforeach;?>
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id="document_approve_script">

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('document/index', array('parent_id' => $document->parent_id)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('document/index', array('parent_id' => $document->parent_id)),
		'spa' => $spa,
)) ?>

<?php endif;?>

$('#approve-button').click(function () { document.getElementById('action').value = 'Approved'; } );
$('#reject-button').click(function () { document.getElementById('action').value = 'Rejected'; } );
</script>
