	<link rel="stylesheet" href="<?php echo $this->basePath('/jClocksGMT-master/css/jClocksGMT.css') ?>">
<?php
$title = $homeSpecs['title'][$locale];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<div>&nbsp;</div>

<?php foreach ($template->specification as $row) : ?>
	<div class="row">
	<?php foreach ($row['specification'] as $entryId => $entryDef) : ?>

		<?php if ($entryDef['type'] == 'banner') : ?>

	    <div <?php if (array_key_exists('class', $entryDef)) echo 'class="'.$entryDef['class'].'"' ?>>
	        <div class="panel">
					<img width="100%" src="<?php echo $this->basePath($place->banner_src) ?>" />
			</div>
		</div>

<!-- Menu -->
		<?php elseif ($entryDef['type'] == 'menuEntry') : ?>

		<div class="col-md-2">
			<div align="center">
			<?php if ($context->isAllowed($entryDef['route'])) : ?>
				<button type="button" class="btn menu-btn <?php echo ($entryId == 'news') ? 'btn-primary' : 'btn-default' ?>" style="width:100%; font-weight: bold; font-size: 110%" id="<?php echo $entryId ?>-anchor">
				<?php if (array_key_exists('glyphicon', $entryDef)) : ?>
					<span class="glyphicon <?php echo $entryDef['glyphicon'] ?>"></span>
				<?php endif;?>
						<?php echo $entryDef['label'][$context->getLocale()] ?>
				</button>
			<?php endif ?>
	
			</div>
		</div>

<!-- Message -->
		<?php elseif ($entryDef['type'] == 'message') : ?>
		
    	<div <?php if (array_key_exists('class', $entryDef)) echo 'class="'.$entryDef['class'].'"' ?>" <?php if (array_key_exists('style', $entryDef)) echo 'style="'.$entryDef['style'].'"' ?>>
    		<?php $first=true; foreach ($entryDef['text'] as $language => $value) : ?>

    		<?php if (!$first) echo '&nbsp;&nbsp;|&nbsp;&nbsp;<em>' ?>
	    		<?php if (array_key_exists('img', $value)) :?>
			<img 
				src="<?php echo $this->basePath($value['img']['src']) ?>" 
				<?php if (array_key_exists('height', $value['img'])) echo 'width="'.$value['img']['height'].'"' ?>
				<?php if (array_key_exists('width', $value['img'])) echo 'width="'.$value['img']['width'].'"' ?>
			/> 
				<?php endif;?>
		    <?php echo $value['text'] ?> 
	    	<?php if (!$first) echo '</em>'?>
	    	
	    	<?php $first=false; endforeach;?>
		</div>

		<?php endif;?>
	
	<?php endforeach;?>
	</div>
<?php endforeach;?>

<?php if (count($homeSpecs['frontProducts']) > 0) : ?>
<!-- Front products -->
<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
						<div class="panel-heading front-page">
				        	<div>
								News
								&nbsp;&nbsp;|&nbsp;&nbsp;
								<img src="<?php echo $this->basePath('img/flags/italia.png') ?>" width="25" /> <em>Informazione</em>
							</div>
				        </div>

<?php $first = true; foreach ($homeSpecs['frontProducts'] as $frontProductId => $frontProduct) : ?>

	<?php $document = $documents['frontProducts'][$frontProductId] ?>
				        <div class="panel-body">
				    		<div id="front_product_<?php echo $frontProductId ?>">

	<h4 style="text-align: center"><?php echo $document->properties['title'] ?></h4>	
	<?php if ($document->image) : ?>
									<div align="center">
										<img 
										<?php foreach ($document->image as $attr => $value) : ?>
											<?php if ($attr == 'src') : ?>
											src="<?php echo $this->basePath($value) ?>"
											<?php else : ?>
											<?php echo $attr ?>="<?php echo $value ?>"
											<?php endif;?>
										<?php endforeach;?>
										/>
									</div>
	<?php endif;?>
			
									<div><?php echo $document->summary ?></div>
									<div style="text-align: center"><a href="<?php echo $this->url('public/displayPage', array('directory' => $frontProduct['directory'], 'name' => $frontProduct['name'])) ?>">Lire la suite...</a></div>
							</div>
				        </div>
 						<hr>
<?php $first = false; endforeach; ?>
 
        </div>
    </div>

</div>
<div>&nbsp;</div>
<?php endif;?>

<div class="row">
    <div class="col-md-12">
        <div class="panel">
			<div class="panel-body">
				<div style="text-align: center">
			        <span id="clock_france"></span>
			        <span id="clock_india"></span>
			        <span id="clock_romania"></span>
			        <span id="clock_uk"></span>
			        <span id="clock_usa"></span>
			    </div>
			</div>
		</div>
	</div>
</div>

<script src="<?php echo $this->basePath('/jClocksGMT-master/js/jquery.rotate.js') ?>"></script>
<script src="<?php echo $this->basePath('/jClocksGMT-master/js/jClocksGMT.js') ?>"></script>

<script>

$(document).ready(function(){

    $('#clock_france').jClocksGMT(
    {   
        title: 'Paris, France', 
        offset: '+1',
        skin: 1,
        digital: false,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

    $('#clock_india').jClocksGMT(
    {
        title: 'Bangalore, India', 
        offset: '+5.5', 
        skin: 1, 
        digital: false,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

    $('#clock_romania').jClocksGMT(
    {   
        title: 'Bucharest, Romania', 
        offset: '+2',
        skin: 1,
        digital: false,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

    $('#clock_uk').jClocksGMT(
    {   
        skin: 1,
        digital: false,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

    $('#clock_usa').jClocksGMT(
    {
        title: 'New York, USA', 
        offset: '-8',
        skin: 1, 
        digital: false,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

    $('#clock_tokyo').jClocksGMT(
    {
        title: 'Tokyo, Japan',
        offset: '+9',
        skin: 1,
        imgpath: '<?php echo $this->basePath('/jClocksGMT-master/') ?>'
    });

});

<?php foreach ($context->getConfig('menus')['p-pit-hr-portal'] as $entryId => $entryDef) : ?>
$('#<?php echo $entryId ?>-anchor').click(function () { $(location).attr('href', '<?php echo $this->url($entryDef['route']) ?>'); });
<?php endforeach;?>


function location_href(target) { document.location.href=target; }
function location_hash(target) { document.location.hash=target; }

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

</script>