				<table class="table-condensed">
					<tr>
						<td colspan="6">
<?php for ($i = 0; $i < count($parent->parents); $i++) : ?>
	<?php if ($i == count($parent->parents)-1) : ?>
				            <strong><?php echo $parent->parents[$i]->name; ?></strong>
	<?php else : ?>
		<?php $p = $parent->parents[$i]; ?>
							<button type="button" class="btn btn-default action-btn directory-anchor" id="directory-anchor_<?php echo $p->id ?>">
								<span><?php echo $p->name ?></span>
							</button> >
	<?php endif;?>
<?php endfor;?>
						</td>
					</tr>
				</table>
				
		    	<table class="table table-striped ppit_index">
					<tr>
						<th>&nbsp;</th>

<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/list'] as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>
					</tr>
					
	<tr>
		<td colspan="4">
			<button type="button" class="btn btn-default index-btn document-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="document-detail-anchor_0">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button>
		</td>
	</tr>
	
<?php foreach ($documents as $document) : ?>
	<tr class="document">
		<td>
			<button type="button" class="btn btn-default index-btn document-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="document-detail-anchor_<?php echo $document->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $document->id ?>-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getInstance()->specifications['ppitDocument']['document/list'] as $propertyId => $rendering) : ?>
		
		<?php $property = $context->getInstance()->specifications['ppitDocument']['document_properties'][$propertyId] ?>

		<?php if ($propertyId == 'type') : ?>
		<td>
			<?php if ($document->type == 'directory') : ?>
			<button type="button" class="btn btn-default directory-anchor" id="directory-anchor_<?php echo $document->id ?>">
				<span class="glyphicon <?php echo $property['modalities'][$document->type]['glyphicon'] ?>"></span>
			</button>
			<?php else : ?>
			<span class="glyphicon glyphicon-file" />
			<?php endif;?>
		</td>
	
		<?php elseif ($propertyId == 'name') : ?>
		<td><?php echo $document->name ?></td>
		
		<?php elseif ($propertyId == 'update_time') : ?>
		<td><?php echo $context->decodeDate($document->update_time) ?></td>
	
		<?php elseif ($propertyId == 'name') : ?>
		<td><?php echo $document->name?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>

	</tr>
<?php endforeach; ?>

</table>
