<style>

@page  
{ 
    size: auto;   /* auto is the initial value */ 

    /* this affects the margin in the printer settings */ 
    margin: 5mm 25mm 5mm 25mm;  
}

.panel-default .panel-heading {
	font-size: 18px;
	text-align: center;
}
.panel-default .front-page {
	background-color: #006179;
	color: #FFF;
	font-size: 18px;
	text-align: center;
}
div.front-page a {
	color: #fff;
}
*.p-pit {
	font-family: sans-serif;
	color: #006179;
	font-weight: bold;
	font-size: 28px;
}
.jumbotron {
	background-color: #FFF;
	color: #555;
}
.row {
	color: #555;
}
blockquote {
	border-left: 4px solid #d6d6d6;
	background: #f9f9f9;
	font-family: "Georgia", "Times New Roman", Times, serif;
	font-size: 18px;
	font-style: italic;
	color: #555;
	line-height: 26px;
}
span.info
{
    position:relative;
}

span.info:hover {z-index:25;}

span.info span{display: none}

span.info:hover span
{
    display:block;
    position:absolute;
    top:2em; left:2em; width:10em;
    border:1px solid #0cf;
    background-color:#fff; color:#fff;
}
.notification {
	font-size: 1.2em;
}

h1.ppit {
	text-align:center;
	font-size: 1.5em;
}

h2.ppit {
	font-size: 1.2em;
}

h3.ppit {
	font-size: 1.0em;
	font-weight: bold
}

h5.ppit {
	font-size: 10px;
	font-weight: bold
}

table.ppit {
	margin-bottom: 20px;
	font-size: 1em;
	width: 100%;
	border-width: 1px; 
 	border-style: solid; 
	border-color: gray;
	border-collapse: collapse;
}

table.ppit caption { 
	font-size:1.2em; 
	padding:1em 0 0.5em 1em;
}

table.ppit th {
	text-align: center;
	color: #666;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
	font-size: 10px;
}

table.ppit td {
	color: #666;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	font-size: 10px;
	padding-bottom: 8px;
	padding-left: 8px;
	padding-right: 8px;
	padding-top: 8px;
}

table.ppit td.title {
	font-weight: bold;
	color: #FFFFFF;
	background-color:#006169;
}

table.ppit td.caption {
	text-align: left;
	font-weight: bold;
}

table.ppit td.number {
	text-align: right;
}

table.ppit td.alert {
	color: red;
	font-weight: bold;
}

table.ppit-address {
	width: 80%;
    margin-left:auto; 
    margin-right:auto;
	border-style: hidden;
}

table.ppit-address tr {
	line-height: 14px;
}

table.ppit-address td {
	border-style: hidden;
	font-size: 12px;
}

table.ppit-bill-rows {
	width: 80%;
    margin-left:auto; 
    margin-right:auto;
}

table.ppit-bill-sums {
	margin-bottom: 20px;
	width: 80%;
    margin-left:auto; 
    margin-right:auto;
	border-style: hidden;
}

table.ppit-bill-sums tr {
	line-height: 10px;
}

table.ppit-bill-sums td {
	border-style: hidden;
	font-size: 10px;
}

div.footer {
	font-size: 0.6em;
}

</style>

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>$this->translate('Expense reports', 'ppit-expense', $context->getLocale());</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link href="<?php echo $this->basePath('css/bootstrap.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
		<link href="<?php echo $this->basePath('css/bootstrap-theme.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
		<link href="<?php echo $this->basePath('css/style.css') ?>" media="screen" rel="stylesheet" type="text/css">
		<link href="<?php echo $this->basePath('img/favicon.ico') ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
		<script type="text/javascript" src="<?php echo $this->basePath('js/jquery.min.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->basePath('js/bootstrap.min.js') ?>"></script>
	</head>
<body>
<?php
echo $this->partial('/partials/pdf-header');
?>
<?php foreach ($document->parts as $part) : ?>
				<?php echo $part->content; ?>
<?php endforeach;?>

				<div class="ppit footer">
					P-PIT – SAS au capital de 10 000 € - R.C.S PARIS 804 199 594<br>
					14, rue Charles V – 75004 PARIS
				</div>
	</body>
</html>