
<div class="container" id="main">
<div>&nbsp;</div>
<?php
$title = $context->localize($template['title']);
$this->headTitle($title);
?>

<!--Main layout-->
	
        <!--Third row-->
        <div class="row">
            <div class="col-md-12">
				<div class="card-block" style="background-color: #FFFFFF" id='calendar'></div>
			</div>
		</div>
	</div>
		
<script>

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

<?php
echo $this->partial('/partials/student-home-scripts');
?>

getEvents(true);

</script>
