
<div class="container" id="main">
	<div>&nbsp;</div>

<?php
if ($context->getLocale() == $document->locale_1 && $document->properties_locale_1) $properties = $document->properties_locale_1;
elseif ($context->getLocale() == $document->locale_2 && $document->properties_locale_2) $properties = $document->properties_locale_2;
else $properties = $document->properties;
$title = $properties['title'];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>
	<section>
		<div>&nbsp;</div>
	
<?php $documentPart = $document->parts[0]; ?>
	
<?php
if ($context->getLocale() == $document->locale_1 && $documentPart->image_locale_1) $image = $documentPart->image_locale_1;
elseif ($context->getLocale() == $document->locale_2 && $documentPart->image_locale_2) $image = $documentPart->image_locale_2;
else $image = $documentPart->image;
?>
	        <div class="row">
	            <div class="col-md-8 col-md-offset-2">
			        <!--Card-->
			        <div class="card">
			
<?php if ($image) : ?>
			            <!--Card image-->
			            <div class="view overlay hm-white-slight">
	<?php if (array_key_exists('href', $image)) : ?>
							<a href="<?php echo $image['href'] ?>" <?php if (array_key_exists('target', $image)) echo 'target="'.$image['target'].'"' ?>>
	<?php endif;?>
							<img 
	<?php foreach ($image as $attr => $value) : ?>
		<?php if ($attr == 'src') : ?>
			<?php if (is_array($value)) $value = $value[rand(0, count($value)-1)]?>
								src="<?php echo $this->basePath($value) ?>"
		<?php elseif ($attr != 'href' && $attr != 'target') : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
		<?php endif;?>
	<?php endforeach;?>
							/>
	<?php if (array_key_exists('href', $image)) : ?>
							</a>
	<?php endif;?>
			                <a href="#">
			                    <div class="mask"></div>
			                </a>
			            </div>
			            <!--/.Card image-->
<?php endif;?>			
			            <!--Card content-->
			            <div class="card-block">
			                <!--Title-->
			                <h4 class="card-title"><?php echo $document->properties['title'] ?></h4>
			                <!--Text-->
	<?php
	if ($context->getLocale() == $document->locale_1 && $documentPart->content_locale_1) $content = $documentPart->content_locale_1;
	elseif ($context->getLocale() == $document->locale_2 && $documentPart->content_locale_2) $content = $documentPart->content_locale_2;
	else $content = $documentPart->content;
	?>
							<div><?php echo $documentPart->content ?></div>

<?php if (array_key_exists('actions', $specifications)) : ?>
	<?php $first=true; foreach ($specifications['actions'] as $actionId => $action) : ?>
		<?php if (!$first) : ?>
					<div>&nbsp;</div>
		<?php endif;?>
					<div style="text-align: center">
		<?php $href = $action['href'] ?>
		<?php if ($href['type'] == 'url') : ?> 
						<button type="button" class="btn btn-success action-btn" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="location_href('<?php echo $actionId ?>', '<?php echo $href['value'] ?>')">
		<?php elseif ($href['type'] == 'route') : ?>
						<button type="button" class="btn btn-success action-btn" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="showForm('<?php echo $actionId ?>', '<?php echo $this->url($href['value'], $href['params'], $href['urlParams']) ?>')">
		<?php elseif ($href['type'] == 'redirect') : ?>
						<button type="button" class="btn btn-success action-btn" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="location_href('<?php echo $actionId ?>', '<?php echo $this->url($href['value'], $href['params']).$href['urlParams'] ?>')">
		<?php endif;?>
							<?php if (isset($action['glyphicon'])) : ?>
							<span class="glyphicon glyphicon-<?php echo $action['glyphicon'] ?>"></span>
							<?php endif;?>
							<?php echo $action['labels'][$context->getLocale()] ?>
						</button>
					</div>
	<?php $first=false; endforeach ?>
<?php endif;?>

					<div>&nbsp;</div>

<?php foreach ($credentials as $identifier => $credential) : ?>
					<hr>
					<div>
	<?php if ($credential->image) : ?>
						<div align="center">
		<?php if (array_key_exists('href', $credential->image)) : ?>
							<a href="<?php echo $credential->image['href'] ?>" <?php if (array_key_exists('target', $credential->image)) echo 'target="'.$credential->image['target'].'"' ?>>
		<?php endif;?>
							<img 
		<?php foreach ($credential->image as $attr => $value) : ?>
			<?php if ($attr == 'src') : ?>
								src="<?php echo $this->basePath($value) ?>"
			<?php elseif ($attr != 'href' && $attr != 'target') : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
			<?php endif;?>
		<?php endforeach;?>
							/>
		<?php if (array_key_exists('href', $credential->image)) : ?>
							</a>
		<?php endif;?>
						</div>
	<?php endif;?>
					</div>
					<div><?php echo $credential->summary ?></div>
					<div style="text-align: center"><a href="<?php echo $this->url('public/displayPage', array('directory' => 'credentials', 'name' => $identifier)) ?>">Lire la suite</a></div>
<?php endforeach;?>
					<div>&nbsp;</div>
				</div>
				<div>
					<a href="https://www.facebook.com/P-PIT-180839485646758/" target="_blank"><img src="<?php echo $this->basePath('/img/facebook.png') ?>" width="24" alt="P-Pit on Facebook" /></a>
					<a href="https://www.linkedin.com/company/confiance-it?trk=biz-companies-cym" target="_blank"><img src="<?php echo $this->basePath('/img/linkedin.png') ?>" width="24" alt="P-Pit on Linkedin" /></a>
					<a href="https://twitter.com/ppitfr" target="_blank"><img src="<?php echo $this->basePath('/img/twitter.png') ?>" width="24" alt="P-Pit on Twitter" /></a>
					<a href="https://plus.google.com/u/1/+Confianceit/posts" target="_blank"><img src="<?php echo $this->basePath('/img/google.png') ?>" width="24" alt="P-Pit on Google" /></a>
					<a href="mailto:?subject=<?php echo $title ?>&body=<?php echo $this->serverUrl(true) ?>" target="_blank"><img src="<?php echo $this->basePath('/img/email.png') ?>" width="24" alt="Share by email" /></a>
				</div>	
			            </div>
			            <!--/.Card content-->
			
			        </div>
			        <!--/.Card-->
	            </div>
	        </section>

<style>
.loader {
	position : fixed;
	z-index: 9999;
//	background : url('<?php echo $this->basePath('/img/loading.gif') ?>') 50% 50% no-repeat;
	background-color: rgba(118, 204, 243, 0.25);
	top : 0px;
	left : 0px;
	height : 100%;
	width : 100%;
	cursor : wait;
}
</style>
<div id="loader" />

<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script>

function location_href(button, target) { 
	document.location.href=target; 
}

$('#form_action').hide();

function showForm(button, target) {

	$('#form_action').show();
	$(location).attr('hash', 'form_action');
	
	var xhttp = new XMLHttpRequest();
	xhttp.open('GET', target, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
			$('#remove-anchor').click(function() { 
				$('#form_action').hide(); 
			});
			connectInstanceTryForm('<?php echo $name ?>');
			$('#caption').focus();
		}
	}
	xhttp.send();
}

<?php 
$properties = array();
$properties['caption'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_first'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_last'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['email'] = array('type' => 'email', 'mandatory' => true, 'maxSize' => 255);
$properties['tel_work'] = array('type' => 'phone', 'mandatory' => true, 'maxSize' => 255);
$properties['username'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['requires_notifications'] = array('type' => 'hidden');
$properties['locale'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Instance', 'context' => $context, 'properties' => $properties)) 
?>

function connectInstanceTryForm(product)
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
	$('#input_<?php echo $propertyId ?>').datepicker();
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

// Check validity
		var validity = checkInstanceUpdateProperties();

		if (validity) {

// Create a new FormData object.
			var formData = new FormData();

// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>

	<?php if ($property['type'] == 'input' || $property['type'] == 'date' || $property['type'] == 'textarea' || $property['type'] == 'select' || $property['type'] == 'number' || $property['type'] == 'email' || $property['type'] == 'phone' || $property['type'] == 'hidden') : ?>
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
			var fileSelect = document.getElementById('order_form');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('order_form', file, file.name);
				}
			}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitment/try') ?>/' + product;
			target = 'form_action';
			xhttp.open('POST', route, true);
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('#remove-anchor').click(function() { 
						$('#form_action').hide(); 
					});
					connectInstanceTryForm();
					$('#loader').removeClass('loader');
				}
			};
			
			$('#loader').addClass('loader');
			xhttp.send(formData);
		}
		else return false;
	}
}

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

</script>