<style>
.blog-content {
	color: #1a1a1a;
	font-family: Merriweather, Georgia, serif;
	font-size: 18px;
	line-height: 1.75;
}</style>

<?php
if ($context->getLocale() == $document->locale_1 && $document->properties_locale_1) $properties = $document->properties_locale_1;
elseif ($context->getLocale() == $document->locale_2 && $document->properties_locale_2) $properties = $document->properties_locale_2;
else $properties = $document->properties;
$title = $properties['title'];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>
<section>
<div>&nbsp;</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading front-page">BLOG</div>
            <div class="panel-body">
       			<div id="front_product_1">

<?php foreach ($entryList as $entryId => $entry) : ?>

	<?php
	if ($context->getLocale() == $entry->locale_1 && $entry->properties_locale_1) $properties = $entry->properties_locale_1;
	elseif ($context->getLocale() == $entry->locale_2 && $entry->properties_locale_2) $properties = $entry->properties_locale_2;
	else $properties = $entry->properties;
	?>

	<?php if ($entryId == $name) : ?>

<!-- Display the document -->
                <h1 style="font-size: 150%; font-width: bold"><?php if (array_key_exists('date',$properties)) echo $context->decodeDate($entry->properties['date']).': ' ?><?php echo $properties['title'] ?></h1>

		<?php for ($i = 0; $i < count($document->parts); $i++) : ?>
			<?php $documentPart = $document->parts[$i]; ?>

					<div id="document_part_panel_<?php echo $documentPart->id ?>">
	
			<?php
			if ($context->getLocale() == $document->locale_1 && $documentPart->image_locale_1) $image = $documentPart->image_locale_1;
			elseif ($context->getLocale() == $document_locale_2 && $documentPart->image_locale_2) $image = $documentPart->image_locale_2;
			else $image = $documentPart->image;
			?>
			<?php if ($image) : ?>
						<div align="center">
				<?php if (array_key_exists('href', $image)) : ?>
							<a href="<?php echo $image['href'] ?>" <?php if (array_key_exists('target', $image)) echo 'target="'.$documentPart->image['target'].'"' ?>>
				<?php endif;?>
							<img 
				<?php foreach ($image as $attr => $value) : ?>
					<?php if ($attr == 'src') : ?>
						<?php if (is_array($value)) $value = $value[rand(0, count($value)-1)]?>
								src="<?php echo $this->basePath($value) ?>"
					<?php elseif ($attr != 'href' && $attr != 'target') : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
					<?php endif;?>
				<?php endforeach;?>
							/>
				<?php if (array_key_exists('href', $image)) : ?>
							</a>
				<?php endif;?>
						</div>
			<?php endif;?>

			<?php
			if ($context->getLocale() == $document->locale_1 && $documentPart->content_locale_1) $content = $documentPart->content_locale_1;
			elseif ($context->getLocale() == $document->locale_2 && $documentPart->content_locale_2) $content = $documentPart->content_locale_2;
			else $content = $documentPart->content;
			?>
						<div class="blog-content"><?php echo $content ?></div>
					</div>
		<?php endfor;?>
	<?php else : ?>
                <a href="<?php echo $this->url('public/displayBlog', array('directory' => $directory, 'name' => $entryId)) ?>"><h1 style="font-size: 110%; margin-top: 10px;"><?php if (array_key_exists('date',$properties)) echo $context->decodeDate($properties['date']).': ' ?><?php echo $properties['title'] ?></h1></a>
	<?php endif;?>
<?php endforeach;?>
					<div>&nbsp;</div>
				</div>
				<div>
					<a href="https://www.facebook.com/P-PIT-180839485646758/" target="_blank"><img src="<?php echo $this->basePath('/img/facebook.png') ?>" width="24" alt="P-Pit on Facebook" /></a>
					<a href="https://www.linkedin.com/company/confiance-it?trk=biz-companies-cym" target="_blank"><img src="<?php echo $this->basePath('/img/linkedin.png') ?>" width="24" alt="P-Pit on Linkedin" /></a>
					<a href="https://twitter.com/ppitfr" target="_blank"><img src="<?php echo $this->basePath('/img/twitter.png') ?>" width="24" alt="P-Pit on Twitter" /></a>
					<a href="https://plus.google.com/u/1/+Confianceit/posts" target="_blank"><img src="<?php echo $this->basePath('/img/google.png') ?>" width="24" alt="P-Pit on Google" /></a>
					<a href="mailto:?subject=<?php echo $title ?>&body=<?php echo $this->serverUrl(true) ?>" target="_blank"><img src="<?php echo $this->basePath('/img/email.png') ?>" width="24" alt="Share by email" /></a>
<!--
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.6";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
					</script>
					<div class="fb-share-button" data-href="https://<?php echo $context->getInstance()->fqdn ?><?php echo $this->url('public/displayPage', array('directory' => $directory, 'name' => $name)) ?>" data-layout="box_count" data-mobile-iframe="true"></div>
	
					<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
					{lang: 'fr'}
					</script>	
					<span class="g-plusone" data-size="tall"></span>
					
					<script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: fr_FR</script>
					<script type="IN/Share" data-url="https://<?php echo $context->getInstance()->fqdn ?><?php echo $this->url('public/displayPage', array('directory' => $directory, 'name' => $name)) ?>" data-counter="top"></script>
	
					<a class="twitter-share-button" href="https://twitter.com/share" data-via="ppitfr">Tweet</a><script>// <![CDATA[
					!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
					// ]]></script> -->
				</div>	
             </div>
        </div>
	</div>

    <div class="col-md-6 col-md-offset-3" id="form_action"></div>
</div>
</section>

<style>
.loader {
	position : fixed;
	z-index: 9999;
//	background : url('<?php echo $this->basePath('/img/loading.gif') ?>') 50% 50% no-repeat;
	background-color: rgba(118, 204, 243, 0.25);
	top : 0px;
	left : 0px;
	height : 100%;
	width : 100%;
	cursor : wait;
}
</style>
<div id="loader" />

<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script>

function location_href(button, target) { 
	document.location.href=target; 
}

$('#form_action').hide();

function showForm(button, target) {

	$('#form_action').show();
	$(location).attr('hash', 'form_action');
	
	var xhttp = new XMLHttpRequest();
	xhttp.open('GET', target, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
			$('#remove-anchor').click(function() { 
				$('#form_action').hide(); 
			});
			connectInstanceTryForm('<?php echo $name ?>');
			$('#caption').focus();
		}
	}
	xhttp.send();
}

<?php 
$properties = array();
$properties['caption'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_first'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_last'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['email'] = array('type' => 'email', 'mandatory' => true, 'maxSize' => 255);
$properties['tel_work'] = array('type' => 'phone', 'mandatory' => true, 'maxSize' => 255);
$properties['username'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['requires_notifications'] = array('type' => 'hidden');
$properties['locale'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Instance', 'context' => $context, 'properties' => $properties)) 
?>

function connectInstanceTryForm(product)
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
	$('#input_<?php echo $propertyId ?>').datepicker();
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

// Check validity
		var validity = checkInstanceUpdateProperties();

		if (validity) {

// Create a new FormData object.
			var formData = new FormData();

// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>

	<?php if ($property['type'] == 'input' || $property['type'] == 'date' || $property['type'] == 'textarea' || $property['type'] == 'select' || $property['type'] == 'number' || $property['type'] == 'email' || $property['type'] == 'phone' || $property['type'] == 'hidden') : ?>
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
			var fileSelect = document.getElementById('order_form');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('order_form', file, file.name);
				}
			}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitment/try') ?>/' + product;
			target = 'form_action';
			xhttp.open('POST', route, true);
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					$('#remove-anchor').click(function() { 
						$('#form_action').hide(); 
					});
					connectInstanceTryForm();
					$('#loader').removeClass('loader');
				}
			};
			
			$('#loader').addClass('loader');
			xhttp.send(formData);
		}
		else return false;
	}
}

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

</script>