<div class="container" id="main">
<div>&nbsp;</div>
	<?php
$title = $context->localize($context->getConfig('public/home')['title']);
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<!--Main layout-->

<div>&nbsp;</div>

        <!--First row-->
        <div class="row">
			<div class="col-md-5">
<?php if (array_key_exists('image', $template)) : ?>
	<?php $image = $template['image'] ?>
	<?php if ($image) : ?>
			    <!--Featured image -->
			    <div class="view overlay hm-white-light z-depth-1-half">
	<?php if (array_key_exists('href', $image)) : ?>
						<a href="<?php echo $image['href'] ?>" <?php if (array_key_exists('target', $image)) echo 'target="'.$image['target'].'"' ?>>
	<?php endif;?>
						<img 
	<?php foreach ($image as $attr => $value) : ?>
		<?php if ($attr == 'src') : ?>
				<?php if (is_array($value)) $value = $value[rand(0, count($value)-1)]?>
							src="<?php echo $this->basePath('img/'.$context->getInstance()->caption.'/'.$value) ?>"
		<?php elseif ($attr != 'href' && $attr != 'target') : ?>
							<?php echo $attr ?>="<?php echo $value ?>"
		<?php endif;?>
	<?php endforeach;?>
						/>
	<?php if (array_key_exists('href', $image)) : ?>
						</a>
	<?php endif;?>
			        <div class="mask">
			        </div>
			    </div>
<?php endif;?>
			</div>
	<?php endif;?>

            <!--Main information-->
            <div class="col-md-7">			
				<div class="card-block" style="background-color: #FFFFFF; color: #686868">
					<h2 style="text-align: center"><?php echo $context->localize($template['title']) ?></h2>
					<hr>
<?php if (array_key_exists('actions', $template)) : ?>
					<div class="row">
	<?php $first=true; foreach ($template['actions'] as $actionId => $action) : ?>
					  <div class="col-md-4">
		<?php $href = $action['href'] ?>
		<?php 
		if ($href['type'] == 'url') $onclick = 'location_href(\''.$actionId.'\', \''.$href['value'].'\')';
		elseif ($href['type'] == 'route') $onclick = 'showForm(\''.$actionId.'\', \''.$this->url($href['value'], $href['params'], $href['urlParams']).'\')';
		elseif ($href['type'] == 'redirect') $onclick = 'location_href(\''.$actionId.'\', \''.$this->url($href['value'], $href['params']).$href['urlParams'].'\')';
		?>
			          	<a class="btn btn-primary" style="width: 100%" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="<?php echo $onclick ?>">
		<?php if (isset($action['glyphicon'])) : ?>
								<i class="fa <?php echo $action['glyphicon'] ?>" aria-hidden="true"></i>
		<?php endif;?>
								<?php echo $action['labels'][$context->getLocale()] ?>
						</a>
					  </div>
	<?php $first=false; endforeach ?>
					</div>
<?php endif;?>
					
				</div>
            </div>
        </div>
        <!--/.First row-->

		<hr>
	
	        <!--Second row-->
	        <div class="row">

	            <div class="col-md-12">
			        <!--Card-->
			        <div class="card">
			
			            <!--Card image-->

			                <img class="card-img-top view overlay hm-white-slight"
							class="img-fluid"
			                />
			                <a href="">
			                    <div class="mask"></div>
			                </a>

			            <!--/.Card image-->
			
			            <!--Card content-->
			            <div class="card-block" style="color: #686868">
			                <!--Text-->
			                <div class="card-text">
			                	<?php echo $context->localize($template['text']) ?>

<?php if (array_key_exists('credentials', $template)) : ?>

					<div>&nbsp;</div>

	<?php foreach ($template['credentials'] as $credentialSpec) : ?>
		<?php $credential = $context->getConfig('public/page/credential')[$credentialSpec['entry']] ?>
					<hr>
					<div>
		<?php if (array_key_exists('summary-image', $credential)) : ?>
						<div align="center">
			<?php if (array_key_exists('href', $credential['summary-image'])) : ?>
							<a href="<?php echo $credential['summary-image']['href'] ?>" <?php if (array_key_exists('target', $credential['image'])) echo 'target="'.$credential['summary-image']['target'].'"' ?>>
			<?php endif;?>
							<img 
			<?php foreach ($credential['summary-image'] as $attr => $value) : ?>
				<?php if ($attr == 'src') : ?>
								src="<?php echo $this->basePath('img/'.$context->getInstance()->caption.'/'.$value) ?>"
				<?php elseif ($attr != 'href' && $attr != 'target') : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
				<?php endif;?>
			<?php endforeach;?>
							/>
			<?php if (array_key_exists('href', $credential['summary-image'])) : ?>
							</a>
			<?php endif;?>
						</div>
		<?php endif;?>
					</div>
					<div><?php echo $context->localize($credential['summary']) ?></div>
					<div style="text-align: center"><a href="<?php echo $this->url('public/displayPage', array('directory' => 'credential', 'name' => $credentialSpec['entry'])) ?>">Lire la suite</a></div>
	<?php endforeach;?>
<?php endif;?>
							</div>
			            </div>
			            <!--/.Card content-->
			
			        </div>
			        <!--/.Card-->
	            </div>
	        </div>
	
	        <!--Third row-->
	        <div class="row">
	            <div class="col-md-12">
	            	<div>&nbsp;</div>
					<div>
						<a href="https://www.facebook.com/P-PIT-180839485646758/" target="_blank"><img src="<?php echo $this->basePath('/img/facebook.png') ?>" width="24" alt="P-Pit on Facebook" /></a>
						<a href="https://www.linkedin.com/company/confiance-it?trk=biz-companies-cym" target="_blank"><img src="<?php echo $this->basePath('/img/linkedin.png') ?>" width="24" alt="P-Pit on Linkedin" /></a>
						<a href="https://twitter.com/ppitfr" target="_blank"><img src="<?php echo $this->basePath('/img/twitter.png') ?>" width="24" alt="P-Pit on Twitter" /></a>
						<a href="https://plus.google.com/u/1/+Confianceit/posts" target="_blank"><img src="<?php echo $this->basePath('/img/google.png') ?>" width="24" alt="P-Pit on Google" /></a>
						<a href="mailto:?subject=<?php echo $title ?>&body=<?php echo $this->serverUrl(true) ?>" target="_blank"><img src="<?php echo $this->basePath('/img/email.png') ?>" width="24" alt="Share by email" /></a>
					</div>
				</div>
			</div>

    <div class="col-md-6 offset-md-3" id="form_action"></div>
</div>

<style>
.loader {
	position : fixed;
	z-index: 9999;
	background-color: rgba(118, 204, 243, 0.25);
	top : 0px;
	left : 0px;
	height : 100%;
	width : 100%;
	cursor : wait;
}
</style>
<div id="loader" />

<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script>

function location_href(button, target) { 
	document.location.href=target; 
}

$('#form_action').hide();

function showForm(button, target) {

	$('#form_action').show();
	$(location).attr('hash', 'form_action');
	
	var xhttp = new XMLHttpRequest();
	xhttp.open('GET', target, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
/*			$('#remove-anchor').click(function() { 
				$('#form_action').hide(); 
			});*/
			connectInstanceTryForm('<?php echo $name ?>');
			$('#caption').focus();
		}
	}
	xhttp.send();
}

<?php 
$properties = array();
$properties['caption'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_title'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_first'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['n_last'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['email'] = array('type' => 'email', 'mandatory' => true, 'maxSize' => 255);
$properties['tel_work'] = array('type' => 'phone', 'mandatory' => true, 'maxSize' => 255);
$properties['username'] = array('type' => 'input', 'mandatory' => true, 'maxSize' => 255);
$properties['requires_notifications'] = array('type' => 'hidden');
$properties['locale'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Instance', 'context' => $context, 'properties' => $properties)) 
?>

function connectInstanceTryForm(product)
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
	$('#input_<?php echo $propertyId ?>').datepicker();
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

// Check validity
		var validity = checkInstanceUpdateProperties();

		if (validity) {

// Create a new FormData object.
			var formData = new FormData();

// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>

	<?php if ($property['type'] == 'input' || $property['type'] == 'date' || $property['type'] == 'textarea' || $property['type'] == 'select' || $property['type'] == 'number' || $property['type'] == 'email' || $property['type'] == 'phone' || $property['type'] == 'hidden') : ?>
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
			var fileSelect = document.getElementById('order_form');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('order_form', file, file.name);
				}
			}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitment/try') ?>/' + product;
			target = 'form_action';
			xhttp.open('POST', route, true);
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
/*					$('#remove-anchor').click(function() { 
						$('#form_action').hide(); 
					});*/
					connectInstanceTryForm();
					$('#loader').removeClass('loader');
				}
			};
			
			$('#loader').addClass('loader');
			xhttp.send(formData);
		}
		else return false;
	}
}

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

</script>