<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $document->properties['title'];
$this->headTitle($title);
echo $context->getHeaderCode();
?>
<div>&nbsp;</div>

<!-- Front product 1 -->
<div class="row">

    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading front-page">
                <div id="front_product_1_title"><?php if (array_key_exists('date',$document->properties)) echo $context->decodeDate($document->properties['date']).': ' ?><?php echo $document->properties['title'] ?></div>
            </div>
            <div class="panel-body">
       			<div id="front_product_1">

<!-- Display the document -->

<?php for ($i = 0; $i < count($document->parts); $i++) : ?>
	<?php $documentPart = $document->parts[$i]; ?>

					<div id="document_part_panel_<?php echo $documentPart->id ?>">
	
	<?php if ($documentPart->image) : ?>
						<div align="center">
							<img 
							<?php foreach ($documentPart->image as $attr => $value) : ?>
								<?php if ($attr == 'src') : ?>
								src="<?php echo $this->basePath($value) ?>"
								<?php else : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
								<?php endif;?>
							<?php endforeach;?>
							/>
						</div>
	<?php endif;?>
			
						<div><?php echo $documentPart->content ?></div>
<?php endfor;?>
					</div>
<?php if (array_key_exists('actions', $content)) : ?>
					<div style="text-align: center">
	<?php foreach ($content['actions'] as $actionId => $action) : ?>
		<?php $href = $action['href'] ?>
		<?php if ($href['type'] == 'url') : ?> 
						<button type="button" class="btn btn-default action-btn" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="<?php echo ($href['type'] == 'url') ? 'location_href' : 'showForm' ?>('<?php echo $actionId ?>', '<?php echo $href['value'] ?>')">
		<?php elseif ($href['type'] == 'route') : ?>
						<button type="button" class="btn btn-default action-btn" id="<?php echo $actionId ?>" title="<?php echo $action['labels'][$context->getLocale()] ?>" onClick="<?php echo ($href['type'] == 'url') ? 'location_href' : 'showForm' ?>('<?php echo $actionId ?>', '<?php echo $this->url($href['value'], $href['params'], $href['urlParams']) ?>')">
		<?php endif;?>
							<?php if (isset($action['glyphicon'])) : ?>
							<span class="glyphicon glyphicon-<?php echo $action['glyphicon'] ?>"></span>&nbsp;
							<?php endif;?>
							<?php echo $action['labels'][$context->getLocale()] ?>
						</button>
	<?php endforeach ?>
					</div>
<?php endif;?>
					<div>&nbsp;</div>
					<div>&nbsp;</div>
				</div>
				<div style="text-align: center">
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.6";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
					</script>
					<div class="fb-share-button" data-href="https://<?php echo $context->getInstance()->fqdn ?><?php echo $this->url('public/displayPage', array('directory' => $directory, 'name' => $name)) ?>" data-layout="box_count" data-mobile-iframe="true"></div>
	
					<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
					{lang: 'fr'}
					</script>	
					<span class="g-plusone" data-size="tall"></span>
					
					<script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: fr_FR</script>
					<script type="IN/Share" data-url="https://<?php echo $context->getInstance()->fqdn ?><?php echo $this->url('public/displayPage', array('directory' => $directory, 'name' => $name)) ?>" data-counter="top"></script>
	
					<a class="twitter-share-button" href="https://twitter.com/share" data-via="ppitfr">Tweet</a><script>// <![CDATA[
					!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
					// ]]></script>
				</div>	
             </div>
        </div>
	</div>

    <div class="col-md-6 col-md-offset-3" id="form_action">
     </div>
</div>

<script>

$('#form_action').hide();

function location_href(button, target) { 
	$('#form_action').hide();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + button).removeClass("btn-default").addClass("btn-primary");

	document.location.href=target; 
}

function showForm(button, target) {

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#' + button).removeClass("btn-default").addClass("btn-primary");

	$('#form_action').show();
	$(location).attr('hash', 'form_action');
	
	var xhttp = new XMLHttpRequest();
	xhttp.open('GET', target, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 <?php if (!$config['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
			document.getElementById('form_action').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('form_action, route = ' + target);
			console.log(xhttp.responseText);
<?php endif;?>

			$('#remove-anchor').click(function() { 
				$('#form_action').hide(); 
				$('.action-btn').removeClass("btn-primary").addClass("btn-default");
			});

			connectAccountRegisterForm();
		}
	}
	xhttp.send();
}

<?php 
$properties = array();

foreach ($context->getConfig('commitmentAccount/register') as $propertyId => $options) {
	$property = $context->getConfig('commitmentAccount')['properties'][$propertyId];
	$properties[$propertyId] = array('type' => $property['type'], 'mandatory' => $options['mandatory'], 'maxSize' => ($property['type'] == 'textarea') ? 2047 : 255);
}
$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Account', 'context' => $context, 'properties' => $properties)) 
?>

function connectAccountRegisterForm()
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
	$('#input_<?php echo $propertyId ?>').datepicker();
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {

		event.preventDefault();

// Check validity
		var validity = checkAccountUpdateProperties();

		if (validity) {

// Create a new FormData object.
			var formData = new FormData();

// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>

	<?php if ($property['type'] == 'input' || $property['type'] == 'date' || $property['type'] == 'textarea' || $property['type'] == 'select' || $property['type'] == 'number' || $property['type'] == 'email' || $property['type'] == 'phone' || $property['type'] == 'hidden') : ?>
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
			var fileSelect = document.getElementById('order_form');
			if (fileSelect) {
				var files = fileSelect.files;
				for (var i = 0; i < files.length; i++) {
					var file = files[i];
					formData.append('order_form', file, file.name);
				}
			}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitmentAccount/register') ?>';
			target = 'form_action';
			xhttp.open('POST', route, true);
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['ppitCoreSettings']['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['ppitCoreSettings']['isTraceActive']) : ?>
					console.log('post, route = ' + route);
					console.log(xhttp.responseText);
<?php endif;?>
					document.getElementById(target).innerHTML = xhttp.responseText;
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

</script>