<style>
.view {
    background: url("<?php echo $this->basePath('img/'.$context->getInstance()->caption.'/IMG_1149.jpg') ?>") no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
</style>

<!--Mask-->
<div class="view hm-black-light">
    <!--Intro content-->
    <div class="full-bg-img flex-center">
        <ul>
            <li>
                <h1 class="h1-responsive">SynApps by <em>P-Pit</em></h1></li>
            <li>
                <p>Explorez vos données</p>
            </li>
            <li>
                <a href="#main" class="btn btn-default btn-lg">Learn more</a>
                <a href="<?php echo $this->url('user/login') ?>" class="btn btn-primary btn-lg">Sign in</a>
            </li>
        </ul>
    </div>
    <!--/Intro content-->
</div>
<!--/.Mask-->

<div class="container" id="main">
<div>&nbsp;</div>
<?php
$title = $homeSpecs['title'][$locale];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<!--Main layout-->

<div>&nbsp;</div>

<?php for ($i = 0; $i < count($documents['jumbotron']->parts); $i++) : ?>
	<?php $documentPart = $documents['jumbotron']->parts[$i]; ?>
        <!--First row-->
        <div class="row">
			<div class="col-md-7">
	<?php
	if ($context->getLocale() == $documents['jumbotron']->locale_1 && $documentPart->image_locale_1) $image = $documentPart->image_locale_1;
	elseif ($context->getLocale() == $documents['jumbotron']->locale_2 && $documentPart->image_locale_2) $image = $documentPart->image_locale_2;
	else $image = $documentPart->image;
	?>
	<?php if ($image) : ?>
			    <!--Featured image -->
			    <div class="view overlay hm-white-light z-depth-1-half">
			        <img
					<?php foreach ($image as $attr => $value) : ?>
						<?php if ($attr == 'src') : ?>
						src="<?php echo $this->basePath($value) ?>"
						<?php else : ?>
						<?php echo $attr ?>="<?php echo $value ?>"
						<?php endif;?>
					<?php endforeach;?>
 					class="img-fluid " alt=""
 			        />
			        <div class="mask">
			        </div>
			    </div>
			</div>
	<?php endif;?>

	<?php
	if ($context->getLocale() == $documents['jumbotron']->locale_1 && $documentPart->content_locale_1) $content = $documentPart->content_locale_1;
	elseif ($context->getLocale() == $documents['jumbotron']->locale_2 && $documentPart->content_locale_2) $content = $documentPart->content_locale_2;
	else $content = $documentPart->content;
	?>
            <!--Main information-->
            <div class="col-md-5" id="document_part_panel_<?php echo $documentPart->id ?>">			
				<div><?php echo $content ?></div>
            </div>
        </div>
        <!--/.First row-->
<?php endfor;?>

		<hr>
	
	        <!--Second row-->
	        <div class="row">

<?php foreach ($homeSpecs['frontProducts'] as $frontProductId => $frontProduct) : ?>
	<?php $document = $documents['frontProducts'][$frontProductId] ?>
	            <div class="col-md-4">
			        <!--Card-->
			        <div class="card">
			
			            <!--Card image-->

			                <img class="card-img-top view overlay hm-white-slight"
							<?php foreach ($document->image as $attr => $value) : ?>
								<?php if ($attr == 'src') : ?>
								src="<?php echo $this->basePath($value) ?>"
								<?php else : ?>
								<?php echo $attr ?>="<?php echo $value ?>"
								<?php endif;?>
							<?php endforeach;?>
							class="img-fluid"
			                />
			                <a href="<?php echo $this->url('public/displayPage', array('directory' => $frontProduct['directory'], 'name' => $frontProduct['name'])) ?>">
			                    <div class="mask"></div>
			                </a>

			            <!--/.Card image-->
			
			            <!--Card content-->
			            <div class="card-block">
			                <!--Title-->
			                <h4 class="card-title"><?php echo $document->properties['title'] ?></h4>
			                <!--Text-->
			                <p class="card-text"><?php echo $document->summary ?></p>
			                <a href="<?php echo $this->url('public/displayPage', array('directory' => $frontProduct['directory'], 'name' => $frontProduct['name'])) ?>" class="btn btn-primary">Lire la suite...</a>
			            </div>
			            <!--/.Card content-->
			
			        </div>
			        <!--/.Card-->
	            </div>
<?php endforeach; ?>

<div>&nbsp;</div>
<div style="text-align: center">
<a href="https://twitter.com/ppitfr" class="twitter-follow-button" data-show-count="false">Follow @ppitfr</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>
</div>
</div>
<script>

<?php if ($fqdn == 'www.p-pit.fr') : ?>
<!-- Google analytics -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-82264844-1', 'auto');
ga('send', 'pageview');
<?php endif;?>

</script>