<?php
	$children = $this->viewModel()->getCurrent()->getChildren();
	$child = $children[0];
	$description = (isset($child->description) ? $child->description : null)
?>
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
    <title>Material Design Bootstrap</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->basePath('mdb-free/css/bootstrap.min.css" rel="stylesheet') ?>">

    <!-- Material Design Bootstrap -->
    <link href="<?php echo $this->basePath('mdb-free/css/mdb.min.css" rel="stylesheet') ?>">

    <!-- Your custom styles (optional) -->
    <link href="<?php echo $this->basePath('mdb-free/css/style.css" rel="stylesheet') ?>">

	<link rel="stylesheet" href="<?php echo $this->basePath('/jquery-ui-1.11.4/jquery-ui.css') ?>">
	<link rel='stylesheet' href="<?php echo $this->basePath('/fullcalendar/fullcalendar.css') ?>" />
	<link rel='stylesheet' href="<?php echo $this->basePath('/css/flipclock.css') ?>" />

    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('mdb-free/js/jquery-2.2.3.min.js') ?>"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('mdb-free/js/tether.min.js') ?>"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('mdb-free/js/bootstrap.min.js') ?>"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('mdb-free/js/mdb.min.js') ?>"></script>

	<script src="<?php echo $this->basePath('/js/jquery.min.js') ?>"></script>
	<script src="<?php echo $this->basePath('/jquery-ui-1.11.4/jquery-ui.js') ?>"></script>
	<script src="<?php echo $this->basePath("ckeditor/ckeditor.js") ?>"></script>
	<script src="<?php echo $this->basePath('/js/moment-with-locales.min.js') ?>"></script>
	<script src="<?php echo $this->basePath('/fullcalendar/fullcalendar.js') ?>"></script>
	<script src="<?php echo $this->basePath('/js/flipclock.min.js') ?>"></script>

</head>

<body>

<?php echo $this->content; ?>
	
	<!--Footer-->
	<footer class="page-footer primary-color-dark center-on-small-only">
	
	    <!--Footer Links-->
	    <div class="container">
	        <div class="row">
	
	            <!--First column-->
	            <div class="col-md-6">
	                <h5 class="title"><?php echo $this->translate('Contact us', 'ppit-document', $child->context->getLocale()) ?></h5>
	                <ul>
<?php if ($child->place->reception_contact && $child->place->reception_contact->tel_work) : ?>
	                	<li>
							<a href="tel:<?php echo $child->place->reception_contact->tel_work ?>"><span class="fa fa-phone fa-lg" aria-hidden="true"></span> <?php echo $child->place->reception_contact->tel_work ?></a>
						</li>
<?php endif;?>

<?php if ($child->place->reception_contact && $child->place->reception_contact->email) : ?>
						<li>
							<a href="mailto:<?php echo $child->place->reception_contact->email ?>"><span class="fa fa-send" aria-hidden="true"></span> Envoyer un email</a>
						</li>
<?php endif;?>
	                	<li>
							<a href="<?php echo $this->url('instance/legalNotices') ?>" rel="follow">Mentions légales</a>
	                	</li>
	                </ul>
	            </div>
	            <!--/.First column-->
	
	            <!--Second column-->
	            <div class="col-md-6">
	                <h5 class="title"><?php echo $this->translate('Resources', 'ppit-core', $child->context->getLocale()) ?></h5>
	                <ul>
	                    <li><a href="<?php echo $this->url('public/displayBlog', array('directory' => 'blog', 'name' => key($child->context->getConfig('ppitDocument')['pages']['blog']))) ?>">Blog</a></li>
	                    <li><a href="https://github.com/2pit-io/2pit.io" target='_blank'>Developer community</a></li>
	                </ul>
	            </div>
	            <!--/.Second column-->
	        </div>
	    </div>
	    <!--/.Footer Links-->
	
	    <!--Copyright-->
	    <div class="footer-copyright">
	        <div class="container-fluid">
	            © 2017 Copyright: <a href="https://mdbootstrap.com"> P-Pit </a>
	
	        </div>
	    </div>
	    <!--/.Copyright-->
	
	</footer>
	<!--/.Footer-->

</body>

</html>